"""Initial

Revision ID: f2923b95bb36
Revises: 
Create Date: 2021-01-26 14:21:03.423768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2923b95bb36'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
                    sa.Column('id', sa.Integer(),
                              nullable=False, comment='城市編號'),
                    sa.Column('name', sa.String(length=100),
                              nullable=False, comment='城市名稱'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user',
                    sa.Column('id', sa.Integer(),
                              nullable=False, comment='使用者編號'),
                    sa.Column('city_id', sa.Integer(),
                              nullable=True, comment='城市編號'),
                    sa.Column('name', sa.String(length=100),
                              nullable=False, comment='使用者名稱'),
                    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('message',
                    sa.Column('id', sa.Integer(),
                              nullable=False, comment='留言編號'),
                    sa.Column('user_id', sa.Integer(),
                              nullable=True, comment='使用者編號'),
                    sa.Column('title', sa.String(length=100),
                              nullable=False, comment='留言標題'),
                    sa.Column('content', sa.String(length=100),
                              nullable=False, comment='留言內容'),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('user')
    op.drop_table('city')
    # ### end Alembic commands ###
